'use strict';
const SONG={id:'enchanted',title:'enchanted love',artist:'linear ring',bpm:190,offset:.2862,dur:130.74,
 sections:[{t:.29,a:[8,6],b:[8,12]},{t:20.50,a:[4,6],b:[4,8]},{t:40.71,a:[4,3],b:[4,8]},
 {t:65.97,a:[4,6],b:[4,3]},{t:81.13,a:[2,4],b:[2,3]},{t:86.18,a:[4,3],b:[4,6]},{t:106.39,a:[8,6],b:[8,8]}]};
const BASE_BPM=SONG.bpm,BASE_OFFSET=SONG.offset,BASE_DUR=SONG.dur,DIV=.10,HALF=.5-DIV,KEY=`boxed.chart.${SONG.id}.v1`,CY='#4fd6e8',OG='#f0913f',ALLOW_CROSS_CHAMBER=false;
const IS_GITHUB_PAGES=location.hostname.endsWith('github.io');
const BASE_SPB=60/BASE_BPM,SECTION_BEATS=SONG.sections.map(s=>(s.t-BASE_OFFSET)/BASE_SPB);
let SPB=60/SONG.bpm;
const tri=u=>{const m=((u%2)+2)%2;return 1-Math.abs(1-m)},BT=t=>(t-SONG.offset)/SPB,TSEC=b=>SONG.offset+b*SPB;
const nextInt=p=>Math.ceil(p-1e-9),nextOdd=p=>{const k=nextInt(p);return k%2?k:k+1},mapX=(c,u)=>c===0?u*HALF:1-u*HALF;
let legs=[[[],[]],[[],[]]],swaps=[];
function impacts(ls){const out=[];for(let i=0;i<ls.length;i++){const L=ls[i],until=i+1<ls.length?ls[i+1].tb0:BT(SONG.dur);if(!L.inv)continue;for(let k=nextInt(L.phi0);;k++){const tb=L.tb0+(k-L.phi0)/L.inv;if(tb>until-1e-9)break;out.push({tb,odd:Math.abs(k%2)===1})}}return out}
function buildEngine(){legs=[[[],[]],[[],[]]];swaps=[];for(let bi=0;bi<2;bi++)for(let ax=0;ax<2;ax++){const ls=legs[bi][ax];for(let si=0;si<SONG.sections.length;si++){const sec=SONG.sections[si],p=(bi?sec.b:sec.a)[ax],inv=p?1/p:0,Tb=SECTION_BEATS[si];if(!ls.length){ls.push({tb0:Tb,phi0:0,inv});continue}const cur=ls.at(-1);if(cur.inv===inv)continue;const phiT=cur.phi0+(Tb-cur.tb0)*cur.inv;let phiS,tbS;if(!cur.inv){phiS=cur.phi0;tbS=Tb}else{phiS=inv===0?nextOdd(phiT):nextInt(phiT);tbS=cur.tb0+(phiS-cur.phi0)/cur.inv}ls.push({tb0:tbS,phi0:phiS,inv})}}
 if(ALLOW_CROSS_CHAMBER){const div=[0,1].map(b=>impacts(legs[b][0]).filter(x=>x.odd).map(x=>TSEC(x.tb)));let cand=[],j=0;for(const a of div[0]){while(j<div[1].length&&div[1][j]<a-.012)j++;if(j<div[1].length&&Math.abs(div[1][j]-a)<=.012)cand.push(a)}let end=-1e9;for(const go of cand){if(go<TSEC(SECTION_BEATS[0])+1.5||go-end<64*SPB)continue;const back=cand.find(b=>b>=go+8*SPB&&b<=go+20*SPB);if(back!==undefined){swaps.push(go,back);end=back}}}
}
function phiAt(ls,bt){let L=ls[0];for(const g of ls){if(g.tb0<=bt+1e-9)L=g;else break}return L.phi0+(bt-L.tb0)*L.inv}
function basePos(bi,t){const bt=BT(t),u=tri(phiAt(legs[bi][0],bt)),v=tri(phiAt(legs[bi][1],bt));let n=0;for(const s of swaps){if(s<=t+1e-9)n++;else break}const c=(bi+n)%2;return[mapX(c,u),v]}
function inferWall(x,y){const q=[[Math.abs(x),'L'],[Math.abs(x-(.5-DIV)),'DL'],[Math.abs(x-(.5+DIV)),'DR'],[Math.abs(x-1),'R'],[Math.abs(y),'T'],[Math.abs(y-1),'B']].sort((a,b)=>a[0]-b[0]);return q[0][1]}
function wallPos(w,x,y){return(w==='L'||w==='DL'||w==='DR'||w==='R')?y:x}
function coords(w,p){if(w==='L')return[0,p];if(w==='DL')return[.5-DIV,p];if(w==='DR')return[.5+DIV,p];if(w==='R')return[1,p];if(w==='T')return[p,0];return[p,1]}
function generated(){buildEngine();let a=[];for(let bi=0;bi<2;bi++){let ts=[...impacts(legs[bi][0]),...impacts(legs[bi][1])].map(e=>TSEC(e.tb)).sort((x,y)=>x-y),last=-9,k=0;for(const t of ts){if(Math.abs(t-last)<1e-7||t>SONG.dur)continue;last=t;const [x,y]=basePos(bi,t),wall=inferWall(x,y);a.push({id:`${bi?'b':'a'}-${String(k++).padStart(3,'0')}`,ball:bi,time:+t.toFixed(6),wall,position:+wallPos(wall,x,y).toFixed(6),source:'generated'})}}return a.sort((x,y)=>x.time-y.time)}
let notes=generated(),selected=null,dirty=false,undo=[],redo=[],drag=null,viewStart=0,follow=true,showTrajectory=true,hitSoundOn=true,seekDragging=false,viewSeekDragging=false,wave=null;
let hitAC=null,hitMaster=null,lastAudioTime=0;
const $=s=>document.querySelector(s),audio=$('#audio'),tl=$('#timeline'),tc=tl.getContext('2d'),box=$('#box'),bc=box.getContext('2d');
function ensureHitAudio(){if(!hitAC){hitAC=new (window.AudioContext||window.webkitAudioContext)();hitMaster=hitAC.createGain();hitMaster.gain.value=.95;hitMaster.connect(hitAC.destination);try{if(navigator.audioSession)navigator.audioSession.type='playback'}catch(_){}try{const s=hitAC.createBufferSource();s.buffer=hitAC.createBuffer(1,1,hitAC.sampleRate);s.connect(hitAC.destination);s.start()}catch(_){}}if(hitAC.state==='suspended')hitAC.resume()}
function playHit(ball,force=false){if(!hitSoundOn&&!force)return;ensureHitAudio();const t=hitAC.currentTime,o=hitAC.createOscillator(),g=hitAC.createGain(),length=Math.ceil(hitAC.sampleRate*.022),buffer=hitAC.createBuffer(1,length,hitAC.sampleRate),samples=buffer.getChannelData(0),noise=hitAC.createBufferSource(),filter=hitAC.createBiquadFilter(),ng=hitAC.createGain();o.type='triangle';o.frequency.setValueAtTime(ball?1850:2450,t);o.frequency.exponentialRampToValueAtTime(ball?820:1120,t+.035);g.gain.setValueAtTime(.0001,t);g.gain.linearRampToValueAtTime(.27,t+.001);g.gain.exponentialRampToValueAtTime(.0001,t+.048);o.connect(g);g.connect(hitMaster);o.start(t);o.stop(t+.055);for(let i=0;i<length;i++)samples[i]=(Math.random()*2-1)*(1-i/length);noise.buffer=buffer;filter.type='highpass';filter.frequency.value=ball?2300:3000;ng.gain.setValueAtTime(.13,t);ng.gain.exponentialRampToValueAtTime(.0001,t+.024);noise.connect(filter);filter.connect(ng);ng.connect(hitMaster);noise.start(t);noise.stop(t+.026);document.documentElement.dataset.lastEditorHit=String(ball);const b=$('#hitSound');b.style.background=ball?OG:CY;b.style.color='#071015';setTimeout(()=>{b.style.background='';b.style.color=''},90)}
function snapshot(){return JSON.stringify({notes,bpm:SONG.bpm,offset:SONG.offset,duration:SONG.dur})}function checkpoint(){undo.push(snapshot());if(undo.length>80)undo.shift();redo=[]}function mark(){dirty=true;$('#status').textContent='有未保存修改';$('#status').className='status dirty';drawAll();syncInspector()}
function setGrid(bpm,offset){if(Number.isFinite(bpm)&&bpm>=20&&bpm<=400)SONG.bpm=bpm;if(Number.isFinite(offset)&&offset>=0&&offset<SONG.dur)SONG.offset=offset;SPB=60/SONG.bpm;$('#bpm').value=SONG.bpm.toFixed(3);$('#offset').value=SONG.offset.toFixed(3)}
function fmtDuration(t){return`${Math.floor(t/60)}:${String(Math.floor(t%60)).padStart(2,'0')}.${String(Math.floor(t%1*1000)).padStart(3,'0')}`}
function setDuration(duration){SONG.dur=Math.max(SONG.offset,Math.min(BASE_DUR,Number.isFinite(duration)?duration:BASE_DUR));$('#seek').max=SONG.dur;$('#duration').textContent=fmtDuration(SONG.dur);$('#endMeasure').value=Math.max(1,Math.round((SONG.dur-SONG.offset)/(4*SPB)));if(audio.currentTime>SONG.dur){audio.currentTime=SONG.dur;lastAudioTime=SONG.dur}viewStart=Math.max(0,Math.min(Math.max(0,SONG.dur-viewDur()),viewStart))}
function restore(s){const d=JSON.parse(s);notes=Array.isArray(d)?d:d.notes;setGrid(d.bpm??SONG.bpm,d.offset??SONG.offset);setDuration(d.duration??BASE_DUR);selected=notes.find(n=>n.id===selected?.id)||null;mark()}
function applyChart(d,label){if(!Array.isArray(d?.notes))return false;setGrid(d.bpm,d.offset);setDuration(d.duration??BASE_DUR);notes=d.notes.filter(n=>n.time<SONG.dur+1e-7);selected=null;dirty=false;$('#status').textContent=label;$('#status').className='status';drawAll();syncInspector();return true}
function loadLocal(){try{return applyChart(JSON.parse(localStorage.getItem(KEY)),'已载入本机人工谱')}catch(_){return false}}
async function loadSaved(){
  try{const r=await fetch(`/api/chart/${SONG.id}`,{cache:'no-store'});if(r.ok&&applyChart(await r.json(),'已载入局域网共享谱'))return}catch(_){}
  if(loadLocal())return;
  try{const r=await fetch(`chart/shared/${SONG.id}.json`,{cache:'no-store'});if(r.ok&&applyChart(await r.json(),'已载入线上共享谱'))return}catch(_){}
}
function payload(){return{version:1,song:SONG.id,bpm:SONG.bpm,offset:SONG.offset,duration:SONG.dur,editedAt:new Date().toISOString(),notes:notes.map(n=>({...n}))}}
function snapTime(t){const q=+$('[id=snap]').value;if(!q)return Math.max(0,Math.min(SONG.dur,t));return Math.max(0,Math.min(SONG.dur,SONG.offset+Math.round((t-SONG.offset)/(SPB/q))*(SPB/q)))}
function resize(){const d=Math.min(devicePixelRatio||1,2);for(const [c,h] of [[tl,300]]){c.width=Math.round(c.clientWidth*d);c.height=Math.round(h*d);c.getContext('2d').setTransform(d,0,0,d,0,0)}drawAll()}
const viewDur=()=>{const bars=+$('#zoom').value;return bars?Math.min(SONG.dur,bars*4*SPB):SONG.dur},xTime=t=>(t-viewStart)/viewDur()*tl.clientWidth,timeX=x=>viewStart+x/tl.clientWidth*viewDur();
function drawTimeline(){const w=tl.clientWidth,h=300;tc.clearRect(0,0,w,h);tc.fillStyle='#111624';tc.fillRect(0,0,w,h);
 const firstBeat=Math.floor((viewStart-SONG.offset)/SPB);const lastBeat=Math.ceil((viewStart+viewDur()-SONG.offset)/SPB);for(let beat=firstBeat;beat<=lastBeat;beat++){const t=SONG.offset+beat*SPB;if(t<0)continue;const x=xTime(t),bar=Math.floor(beat/4),down=((beat%4)+4)%4===0;tc.strokeStyle=down?'#3c4863':'#202a3e';tc.lineWidth=down?1.5:1;tc.beginPath();tc.moveTo(x,0);tc.lineTo(x,h);tc.stroke();if(down){tc.fillStyle='#738099';tc.font='10px sans-serif';tc.fillText(bar>=0?`${bar+1} 小节`:`前奏`,x+4,13)}else if(viewDur()<20){tc.fillStyle='#4d5870';tc.font='9px sans-serif';tc.fillText(`${((beat%4)+4)%4+1}`,x+3,13)}}
 if(wave){tc.beginPath();for(let i=0;i<w;i++){const t=timeX(i),idx=Math.min(wave.length-1,Math.floor(t/BASE_DUR*wave.length)),a=wave[idx];tc.lineTo(i,70-a*50)}tc.lineTo(w,70);tc.lineTo(0,70);tc.fillStyle='#8190aa22';tc.fill()}
 for(const [bi,y] of [[0,142],[1,226]]){tc.fillStyle=bi?OG:CY;tc.globalAlpha=.08;tc.fillRect(0,y-32,w,64);tc.globalAlpha=1;tc.fillStyle='#6f7b93';tc.font='11px sans-serif';tc.fillText(bi?'橙球':'青球',8,y-39)}
 for(const n of notes){if(n.time<viewStart||n.time>viewStart+viewDur())continue;const x=xTime(n.time),y=n.ball?226:142;tc.strokeStyle=n.ball?OG:CY;tc.lineWidth=n===selected?5:3;tc.beginPath();tc.moveTo(x,y-23);tc.lineTo(x,y+23);tc.stroke();if(n===selected){tc.strokeStyle='#fff';tc.lineWidth=1;tc.strokeRect(x-6,y-28,12,56)}}
 const px=xTime(audio.currentTime);if(px>=0&&px<=w){tc.strokeStyle='#fff';tc.lineWidth=1;tc.beginPath();tc.moveTo(px,0);tc.lineTo(px,h);tc.stroke();tc.fillStyle='#fff';tc.beginPath();tc.moveTo(px-6,0);tc.lineTo(px+6,0);tc.lineTo(px,9);tc.closePath();tc.fill()}}
function interp(bi,t){const a=notes.filter(n=>n.ball===bi).sort((x,y)=>x.time-y.time);if(!a.length)return[bi,0.5];let j=a.findIndex(n=>n.time>=t);if(j<0)j=a.length-1;if(j===0)return coords(a[0].wall,a[0].position);const p=a[j-1],n=a[j],u=Math.max(0,Math.min(1,(t-p.time)/(n.time-p.time||1)));const A=coords(p.wall,p.position),B=coords(n.wall,n.position);return[A[0]+(B[0]-A[0])*u,A[1]+(B[1]-A[1])*u]}
function previewTime(){return audio.paused&&selected?selected.time:audio.currentTime}
function drawBox(){const s=620,p=42,sz=s-p*2,now=previewTime(),xy=([x,y])=>[p+x*sz,p+y*sz];bc.clearRect(0,0,s,s);bc.fillStyle='#0c1120';bc.fillRect(p,p,sz,sz);bc.fillStyle='#142037';bc.fillRect(p,p,sz*.4,sz);bc.fillStyle='#291d19';bc.fillRect(p+sz*.6,p,sz*.4,sz);bc.fillStyle='#263149';bc.fillRect(p+sz*.4-9,p,18,sz);bc.fillRect(p+sz*.6-9,p,18,sz);
 bc.strokeStyle='#46516b';bc.lineWidth=4;bc.strokeRect(p,p,sz,sz);
 if(showTrajectory){
   for(let bi=0;bi<2;bi++){
     const future=notes.filter(n=>n.ball===bi&&n.time>=now).sort((a,b)=>a.time-b.time).slice(0,5);
     const pts=[interp(bi,now),...future.map(n=>coords(n.wall,n.position))].map(xy);
     if(pts.length>1){bc.beginPath();bc.moveTo(...pts[0]);for(let i=1;i<pts.length;i++)bc.lineTo(...pts[i]);bc.strokeStyle=(bi?OG:CY)+'99';bc.lineWidth=3;bc.setLineDash([8,9]);bc.stroke();bc.setLineDash([])}
   }
   if(selected){
     const same=notes.filter(n=>n.ball===selected.ball).sort((a,b)=>a.time-b.time),i=same.indexOf(selected),local=same.slice(Math.max(0,i-1),i+2).map(n=>xy(coords(n.wall,n.position)));
     if(local.length>1){bc.beginPath();bc.moveTo(...local[0]);for(let j=1;j<local.length;j++)bc.lineTo(...local[j]);bc.strokeStyle='#ffffffcc';bc.lineWidth=4;bc.stroke()}
   }
 }
 for(let bi=0;bi<2;bi++){const [x,y]=xy(interp(bi,now));bc.beginPath();bc.arc(x,y,13,0,7);bc.fillStyle=bi?OG:CY;bc.shadowColor=bc.fillStyle;bc.shadowBlur=22;bc.fill();bc.shadowBlur=0}
 if(selected){const [x,y]=xy(coords(selected.wall,selected.position));bc.beginPath();bc.arc(x,y,27,0,7);bc.strokeStyle='#fff';bc.lineWidth=3;bc.stroke();bc.fillStyle='#fff';bc.font='12px sans-serif';bc.fillText(`${selected.time.toFixed(3)}s`,Math.min(s-95,x+18),Math.max(20,y-18))}}
function syncViewSeek(){const max=Math.max(0,SONG.dur-viewDur()),bar=$('#viewSeek');bar.max=max;bar.disabled=max<.001;if(!viewSeekDragging)bar.value=Math.min(max,viewStart);const beat=(viewStart-SONG.offset)/SPB,measure=Math.max(1,Math.floor(beat/4)+1);$('#viewLabel').textContent=max<.001?'显示全曲':`第 ${measure} 小节起`}
function drawAll(){$('#count').textContent=`${notes.length} 个音符`;syncViewSeek();drawTimeline();drawBox()}function clock(){let t=audio.currentTime;if(!audio.paused&&t>=SONG.dur){audio.pause();audio.currentTime=SONG.dur;t=SONG.dur}const dt=t-lastAudioTime;if(!audio.paused&&dt>=0&&dt<.14){for(const n of notes)if(n.time>lastAudioTime&&n.time<=t+.002)playHit(n.ball)}lastAudioTime=t;if(!seekDragging)$('#seek').value=t;$('#clock').textContent=`${Math.floor(t/60)}:${String(Math.floor(t%60)).padStart(2,'0')}.${String(Math.floor(t%1*1000)).padStart(3,'0')}`;const bar=Math.max(0,Math.floor((t-SONG.offset)/(SPB*4)));$('#measureStatus').textContent=`播放头位于第 ${bar+1} 小节`;if(follow&&viewDur()<SONG.dur&&(t<viewStart||t>viewStart+viewDur()*.86))viewStart=Math.max(0,Math.min(SONG.dur-viewDur(),t-viewDur()*.15));drawAll();requestAnimationFrame(clock)}
function syncInspector(){const on=!!selected;for(const id of ['ball','ntime','wall','pos','posnum','del'])$('#'+id).disabled=!on;$('#nid').textContent=selected?.id||'未选择';if(!on){$('#warn').textContent='';return}$('#ball').value=selected.ball;$('#ntime').value=selected.time.toFixed(3);$('#wall').value=selected.wall;$('#pos').value=selected.position;$('#posnum').value=selected.position.toFixed(3);validate()}
function validate(){if(!selected)return;let msg='';const [x,y]=coords(selected.wall,selected.position);for(const n of notes){if(n===selected||n.ball===selected.ball||Math.abs(n.time-selected.time)>.12)continue;const q=coords(n.wall,n.position);if(Math.hypot((x-q[0])*520,(y-q[1])*520)<72)msg='警告：两球同时音符的落点可能互相混淆。'}$('#warn').textContent=msg}
function chooseAt(x,y){let best=null,d=16;for(const n of notes){const nx=xTime(n.time),ny=n.ball?226:142,dd=Math.hypot(nx-x,(ny-y)*.35);if(dd<d){d=dd;best=n}}selected=best;syncInspector();drawAll();return best}
function scrubAt(e){const r=tl.getBoundingClientRect();audio.currentTime=Math.max(0,Math.min(SONG.dur,timeX(e.clientX-r.left)));drawAll()}
tl.addEventListener('pointerdown',e=>{const r=tl.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,onPlayhead=Math.abs(x-xTime(audio.currentTime))<=12||y<=28,n=onPlayhead?null:chooseAt(x,y);tl.setPointerCapture(e.pointerId);if(n){checkpoint();drag={kind:'note',n,start:n.time};if(audio.paused){audio.currentTime=n.time;lastAudioTime=n.time}}else{selected=null;syncInspector();drag={kind:'scrub'};scrubAt(e)}});
tl.addEventListener('pointermove',e=>{if(drag?.kind==='scrub'){scrubAt(e);return}if(drag?.kind!=='note')return;const r=tl.getBoundingClientRect();drag.n.time=snapTime(timeX(e.clientX-r.left));notes.sort((a,b)=>a.time-b.time);if(audio.paused){audio.currentTime=drag.n.time;lastAudioTime=drag.n.time}mark()});
tl.addEventListener('pointerup',()=>drag=null);tl.addEventListener('pointercancel',()=>drag=null);
const seek=$('#seek'),beginSeek=()=>{seekDragging=true;selected=null;syncInspector()},endSeek=()=>seekDragging=false;seek.addEventListener('pointerdown',beginSeek);seek.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End','PageUp','PageDown'].includes(e.key))beginSeek()});seek.addEventListener('input',e=>{const t=Math.max(0,Math.min(SONG.dur,+e.target.value));audio.currentTime=t;lastAudioTime=t;drawAll()});for(const ev of ['pointerup','pointercancel','change','keyup','blur'])seek.addEventListener(ev,endSeek);addEventListener('pointerup',endSeek);addEventListener('pointercancel',endSeek);
$('#viewSeek').addEventListener('pointerdown',()=>viewSeekDragging=true);$('#viewSeek').addEventListener('input',e=>{viewStart=Math.max(0,Math.min(SONG.dur-viewDur(),+e.target.value));follow=false;$('#follow').textContent='跟随：关';drawAll()});for(const ev of ['pointerup','pointercancel','change'])$('#viewSeek').addEventListener(ev,()=>{viewSeekDragging=false;syncViewSeek()});
tl.addEventListener('wheel',e=>{e.preventDefault();viewStart=Math.max(0,Math.min(SONG.dur-viewDur(),viewStart+e.deltaY/tl.clientWidth*viewDur()));follow=false;$('#follow').textContent='跟随：关';drawAll()},{passive:false});
box.addEventListener('pointerdown',e=>{if(!selected)return;checkpoint();box.setPointerCapture(e.pointerId);drag={box:true};moveBox(e)});box.addEventListener('pointermove',e=>{if(drag?.box)moveBox(e)});box.addEventListener('pointerup',()=>drag=null);
function moveBox(e){const r=box.getBoundingClientRect(),x=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y=Math.max(0,Math.min(1,(e.clientY-r.top)/r.height));selected.position=(['L','DL','DR','R'].includes(selected.wall)?y:x);mark()}
function editField(mut){if(!selected)return;checkpoint();mut();notes.sort((a,b)=>a.time-b.time);mark()}
$('#ball').onchange=e=>editField(()=>selected.ball=+e.target.value);$('#ntime').onchange=e=>editField(()=>{selected.time=snapTime(+e.target.value);if(audio.paused){audio.currentTime=selected.time;lastAudioTime=selected.time}});$('#wall').onchange=e=>editField(()=>selected.wall=e.target.value);for(const id of ['pos','posnum'])$('#'+id).oninput=e=>{if(!selected)return;if(!drag){checkpoint();drag={field:true}}selected.position=Math.max(0,Math.min(1,+e.target.value));mark()};for(const id of ['pos','posnum'])$('#'+id).onchange=()=>drag=null;
function add(ball){checkpoint();const wall=ball?'R':'L',id=`custom-${Date.now().toString(36)}`;selected={id,ball,time:snapTime(audio.currentTime),wall,position:.5,source:'custom'};notes.push(selected);notes.sort((a,b)=>a.time-b.time);mark()}
$('#add0').onclick=()=>add(0);$('#add1').onclick=()=>add(1);$('#del').onclick=()=>{if(!selected)return;checkpoint();notes=notes.filter(n=>n!==selected);selected=null;mark()};
const PATHS=[[
 ['L',.22],['T',.22],['DL',.72],['B',.34],['L',.82],['T',.35],['DL',.28],['B',.18]
],[
 ['R',.78],['B',.78],['DR',.28],['T',.66],['R',.18],['B',.65],['DR',.72],['T',.82]
]];
function fillMeasure(ball,divisions,label){checkpoint();const bar=Math.max(0,Math.floor((audio.currentTime-SONG.offset)/(SPB*4))),start=SONG.offset+bar*4*SPB,end=start+4*SPB,oldPrefix=`grid-${bar}-`,kept=notes.filter(n=>n.ball!==ball||((n.time<start-1e-7||n.time>=end-1e-7)&&!(n.source==='grid'&&n.id.startsWith(oldPrefix)))),count=4*divisions,made=[];for(let i=0;i<count;i++){const [wall,position]=PATHS[ball][i%PATHS[ball].length];made.push({id:`grid-${bar}-${ball}-${divisions}-${String(i).padStart(2,'0')}`,ball,time:+(start+i*SPB/divisions).toFixed(6),wall,position,source:'grid'})}notes=[...kept,...made].sort((a,b)=>a.time-b.time);selected=null;mark();$('#status').textContent=`第 ${bar+1} 小节：${ball?'橙球':'青球'}已铺 ${count} 个${label} · 尚未保存`}
function pathCandidates(ball){const side=ball?'R':'L',divider=ball?'DR':'DL',edge=ball?[.64,.78,.92]:[.08,.22,.36],out=[];for(const p of [.16,.34,.52,.70,.86])out.push([side,p],[divider,p]);for(const p of edge)out.push(['T',p],['B',p]);return out}
function pointDistance(a,b){const A=coords(a.wall,a.position),B=coords(b.wall,b.position);return Math.hypot(A[0]-B[0],A[1]-B[1])}
function timelineEvents(ordered){const events=[];for(const n of ordered){const last=events.at(-1);if(last&&Math.abs(n.time-last.time)<=.03)last.notes.push(n);else events.push({time:n.time,notes:[n]})}return events}
function sparseNotes(events){const out=new Set();for(let i=0;i<events.length;i++){const e=events[i],prev=i?e.time-events[i-1].time:Infinity,next=i+1<events.length?events[i+1].time-e.time:Infinity;if(e.notes.length===1&&prev>=SPB*.9&&next>=SPB*.9)out.add(e.notes[0])}return out}
function alternateSparseHands(events,sparse){let lastHand=null,changed=0;for(const e of events){if(sparse.has(e.notes[0])){const n=e.notes[0],desired=lastHand===null?n.ball:1-lastHand;if(n.ball!==desired){n.ball=desired;changed++}lastHand=n.ball}else if(e.notes.length===1)lastHand=e.notes[0].ball;else lastHand=null}return changed}
function mirrorPoint([wall,position]){return[{L:'R',DL:'DR',DR:'DL',R:'L',T:'T',B:'B'}[wall],(wall==='T'||wall==='B')?1-position:position]}
function arrangeSymmetricTriplets(ordered){const group=ordered.filter(n=>{const beat=(n.time-SONG.offset)/SPB,bar=Math.floor(beat/4)+1,inBar=beat-(bar-1)*4;return bar===31||(bar===32&&inBar<1.01)}),left=group.filter(n=>n.ball===0),right=group.filter(n=>n.ball===1),path=[['L',.30],['B',.24],['DL',.68],['T',.24],['L',.72],['B',.38],['DL',.32],['T',.38]];for(let i=0;i<Math.min(path.length,left.length);i++){[left[i].wall,left[i].position]=path[i]}for(let i=0;i<Math.min(path.length,right.length);i++){[right[i].wall,right[i].position]=mirrorPoint(path[i])}return Math.min(path.length,left.length)+Math.min(path.length,right.length)}
function generatePaths(){checkpoint();const ordered=notes.slice().sort((a,b)=>a.time-b.time),events=timelineEvents(ordered),sparse=sparseNotes(events),handChanges=alternateSparseHands(events,sparse),state=[{last:null,route:0},{last:null,route:0}],placed=[];let compact=0;for(const n of ordered){const s=state[n.ball],gap=s.last?n.time-s.last.time:Infinity;if(s.last&&gap<=SPB*1.25){const recent=placed.filter(p=>n.time-p.time<=.85),all=pathCandidates(n.ball),near=all.map(([wall,position])=>({wall,position})).filter(p=>{const d=pointDistance(s.last,p);return d>=.26&&d<=.46}),pool=near.length?near:all.map(([wall,position])=>({wall,position}));let best=pool[0],score=-Infinity;for(const p of pool){const move=pointDistance(s.last,p),clearance=recent.length?Math.min(...recent.map(q=>pointDistance(q,p))):1,value=clearance-move*.22+(p.wall!==s.last.wall ? .06 : 0);if(value>score){score=value;best=p}}n.wall=best.wall;n.position=best.position;compact++}else{const [wall,position]=PATHS[n.ball][s.route++%PATHS[n.ball].length];n.wall=wall;n.position=position}if((n.ball===0&&n.wall==='DR')||(n.ball===1&&n.wall==='DL'))n.wall=n.ball?'DR':'DL';n.position=+n.position.toFixed(6);n.source=n.source==='generated'?'generated-path':n.source;s.last={time:n.time,wall:n.wall,position:n.position};placed.push(s.last)}const symmetric=arrangeSymmetricTriplets(ordered);selected=null;mark();$('#status').textContent=`已生成轨迹 · 31–32 小节 ${symmetric} 个三连音镜像编排 · 不跨舱 · ${handChanges} 个稀疏单音换手 · 时间与总数未改变`}
function keepInChambers(){const crossing=notes.filter(n=>(n.ball===0&&(n.wall==='R'||n.wall==='DR'))||(n.ball===1&&(n.wall==='L'||n.wall==='DL')));if(!crossing.length){$('#status').textContent='当前谱面已经没有跨舱落点';return}checkpoint();for(const n of crossing){if(n.ball===0)n.wall=n.wall==='R'?'L':'DL';else n.wall=n.wall==='L'?'R':'DR'}selected=null;mark();$('#status').textContent=`已取消 ${crossing.length} 个跨舱落点 · 尚未保存`}
for(const [prefix,ball] of [['Cy',0],['Og',1]])for(const [name,division,label] of [['Quarter',1,'四分音符'],['Eighth',2,'八分音符'],['Triplet',3,'三连音'],['Sixteenth',4,'十六分音符']])$('#fill'+prefix+name).onclick=()=>fillMeasure(ball,division,label);$('#generatePaths').onclick=generatePaths;$('#keepInChambers').onclick=keepInChambers;
$('#play').onclick=()=>{if(audio.paused){ensureHitAudio();lastAudioTime=audio.currentTime;audio.play();$('#play').textContent='❚❚ 暂停'}else{audio.pause();$('#play').textContent='▶ 播放'}};$('#stop').onclick=()=>{audio.pause();audio.currentTime=0;lastAudioTime=0;$('#play').textContent='▶ 播放'};audio.onpause=()=>$('#play').textContent='▶ 播放';
$('#zoom').onchange=()=>{viewStart=Math.max(0,Math.min(SONG.dur-viewDur(),audio.currentTime-viewDur()/2));drawAll()};$('#follow').onclick=()=>{follow=!follow;$('#follow').textContent='跟随：'+(follow?'开':'关')};$('#trajectory').onclick=()=>{showTrajectory=!showTrajectory;$('#trajectory').textContent='轨迹：'+(showTrajectory?'开':'关');drawBox()};
$('#hitSound').onclick=()=>{hitSoundOn=!hitSoundOn;$('#hitSound').textContent='打击音：'+(hitSoundOn?'开':'关');if(hitSoundOn)ensureHitAudio()};
$('#testCy').onclick=()=>playHit(0,true);$('#testOg').onclick=()=>playHit(1,true);
for(const id of ['bpm','offset'])$('#'+id).onfocus=()=>checkpoint();
$('#bpm').oninput=e=>{const v=+e.target.value;if(v>=20&&v<=400){SONG.bpm=v;SPB=60/v;viewStart=Math.max(0,Math.min(SONG.dur-viewDur(),viewStart));mark()}};
$('#offset').oninput=e=>{const v=+e.target.value;if(v>=0&&v<SONG.dur){SONG.offset=v;mark()}};
$('#bpm').onchange=()=>setGrid(SONG.bpm,SONG.offset);$('#offset').onchange=()=>setGrid(SONG.bpm,SONG.offset);
$('#offsetNow').onclick=()=>{checkpoint();setGrid(SONG.bpm,audio.currentTime);mark()};
$('#applyEnd').onclick=()=>{const measures=Math.max(1,Math.floor(+$('#endMeasure').value||1)),cutoff=Math.min(BASE_DUR,SONG.offset+measures*4*SPB);checkpoint();const before=notes.length;audio.pause();setDuration(cutoff);notes=notes.filter(n=>n.time<cutoff-1e-7);if(selected&&!notes.includes(selected))selected=null;mark();$('#status').textContent=`已截到第 ${$('#endMeasure').value} 小节末（${fmtDuration(SONG.dur)}）· 删除 ${before-notes.length} 个后续音符 · 尚未保存`};
$('#regenerate').onclick=()=>{checkpoint();notes=generated();selected=null;viewStart=Math.max(0,Math.min(SONG.dur-viewDur(),audio.currentTime-viewDur()*.15));mark();$('#status').textContent=`已按 ${SONG.bpm.toFixed(3)} BPM 重新生成 · 尚未保存`};
$('#undo').onclick=()=>{if(!undo.length)return;redo.push(snapshot());restore(undo.pop())};$('#redo').onclick=()=>{if(!redo.length)return;undo.push(snapshot());restore(redo.pop())};
$('#save').onclick=async()=>{
  const button=$('#save'),data=payload();
  localStorage.setItem(KEY,JSON.stringify(data));
  if(IS_GITHUB_PAGES){
    dirty=false;
    $('#status').textContent=`已保存到此浏览器 · ${data.notes.length} 个音符 · 分享请导出 JSON`;
    $('#status').className='status';
    return;
  }
  button.disabled=true;$('#status').textContent='正在保存共享谱…';
  try{const r=await fetch(`/api/chart/${SONG.id}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),answer=await r.json();if(!r.ok||!answer.ok)throw Error(answer.error||'服务器拒绝保存');dirty=false;$('#status').textContent=`已保存局域网共享谱 · ${answer.notes} 个音符`;$('#status').className='status'}catch(err){dirty=true;$('#status').textContent=`仅保存到本机 · 共享保存失败：${err.message}`;$('#status').className='status dirty'}finally{button.disabled=false}
};
$('#export').onclick=()=>{const a=document.createElement('a'),blob=new Blob([JSON.stringify(payload(),null,2)],{type:'application/json'});a.href=URL.createObjectURL(blob);a.download=`${SONG.id}-play.json`;a.click();URL.revokeObjectURL(a.href)};
$('#import').onclick=()=>$('#file').click();$('#file').onchange=async e=>{try{const d=JSON.parse(await e.target.files[0].text());if(d.song!==SONG.id||!Array.isArray(d.notes))throw Error('不是 enchanted 的有效谱面');checkpoint();notes=d.notes;setGrid(d.bpm??SONG.bpm,d.offset??SONG.offset);selected=null;mark()}catch(err){alert(err.message)}e.target.value=''};
$('#simplifyTail').onclick=()=>{const after=Math.max(0,Math.floor(+$('#tailAfter').value||0)),cutoff=SONG.offset+after*4*SPB,before=notes.filter(n=>n.time<cutoff-1e-7),tail=notes.filter(n=>n.time>=cutoff-1e-7).sort((a,b)=>a.time-b.time),slots=new Map();for(const n of tail){const beat=Math.round((n.time-SONG.offset)/SPB),time=SONG.offset+beat*SPB;if(time>=SONG.dur-1e-7)continue;const old=slots.get(beat);if(!old||Math.abs(n.time-time)<Math.abs(old.originalTime-time))slots.set(beat,{note:n,originalTime:n.time,time})}const kept=[...slots.values()].sort((a,b)=>a.time-b.time).map(x=>({...x.note,time:x.time,source:x.note.source==='custom'?'custom':'tail-quarter'})),removed=tail.length-kept.length;if(!removed){$('#status').textContent=`第 ${after} 小节之后已经符合 1 拍节奏`;return}checkpoint();notes=[...before,...kept].sort((a,b)=>a.time-b.time);selected=null;mark();$('#status').textContent=`第 ${after} 小节之后已改为 1 拍节奏 · 删除 ${removed} 个密集音符 · 尚未保存`};
$('#simplify').onclick=()=>{const barDur=4*SPB,barCount=Math.ceil((SONG.dur-SONG.offset)/barDur),next=[];let changedBars=0,removed=0;for(let bar=0;bar<barCount;bar++){const start=SONG.offset+bar*barDur,end=Math.min(SONG.dur,start+barDur),group=notes.filter(n=>n.time>=start-1e-7&&n.time<end-1e-7).sort((a,b)=>a.time-b.time);if(group.length<12){next.push(...group);continue}changedBars++;removed+=group.length-8;const pool=group.slice();for(let slot=0;slot<8;slot++){const target=start+slot*SPB/2;let best=0;for(let i=1;i<pool.length;i++)if(Math.abs(pool[i].time-target)<Math.abs(pool[best].time-target))best=i;const n=pool.splice(best,1)[0];next.push({...n,time:+target.toFixed(6)})}}if(!changedBars){$('#status').textContent='没有达到轻度简化条件的高密小节';return}checkpoint();const beforeStart=SONG.offset,beforeEnd=SONG.offset+barCount*barDur;notes=[...notes.filter(n=>n.time<beforeStart-1e-7||n.time>=beforeEnd-1e-7),...next].sort((a,b)=>a.time-b.time);selected=null;mark();$('#status').textContent=`已轻度简化 ${changedBars} 个高密小节 · 减少 ${removed} 个音符 · 尚未保存`};
$('#clearAll').onclick=()=>{if(!notes.length)return;if(!confirm(`确定清空全部 ${notes.length} 个音符？清空后可以撤销，保存前不会影响共享谱面。`))return;checkpoint();notes=[];selected=null;mark();$('#status').textContent='已清空所有音符 · 尚未保存'};
$('#reset').onclick=()=>{if(!confirm('恢复自动生成的初稿？当前未导出的修改会丢失。'))return;checkpoint();setGrid(BASE_BPM,BASE_OFFSET);setDuration(BASE_DUR);notes=generated();selected=null;localStorage.removeItem(KEY);mark()};
addEventListener('keydown',e=>{const active=document.activeElement,typing=active.matches?.('input[type=number],select');if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?$('#redo').click():$('#undo').click();return}if(typing)return;if(e.key==='Delete'||e.key==='Backspace'){$('#del').click();return}if(e.code==='Space'){e.preventDefault();$('#play').click();return}if(e.repeat)return;if(e.code==='KeyF'||e.code==='KeyJ'){e.preventDefault();add(e.code==='KeyJ'?1:0)}});
async function waveform(){try{const ab=await(await fetch(audio.src)).arrayBuffer(),ac=new AudioContext(),b=await ac.decodeAudioData(ab),d=b.getChannelData(0),N=2400;wave=new Float32Array(N);for(let i=0;i<N;i++){let m=0,a=Math.floor(i*d.length/N),z=Math.floor((i+1)*d.length/N);for(let j=a;j<z;j+=8)m=Math.max(m,Math.abs(d[j]));wave[i]=m}ac.close();drawAll()}catch(_){}}
if(IS_GITHUB_PAGES)$('#save').textContent='保存到浏览器';
setGrid(SONG.bpm,SONG.offset);setDuration(BASE_DUR);loadSaved();syncInspector();resize();addEventListener('resize',resize);waveform();clock();
